name: CD
on:
  push:
    branches:
      - main
  pull_request_target:
    types: [closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  update_env:
    if: github.event_name != 'pull_request_target' || (github.event_name == 'pull_request_target' && github.event.pull_request.merged == true)
    uses: ./.github/workflows/env_update.yml
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_SUDO: ${{ secrets.SSH_SUDO }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      SSH_DOMIAN: ${{ secrets.SSH_DOMIAN }}
  update_mvn:
    if: github.event_name != 'pull_request_target' || (github.event_name == 'pull_request_target' && github.event.pull_request.merged == true)
    uses: ./.github/workflows/mvn_update.yml
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_SUDO: ${{ secrets.SSH_SUDO }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
  update_npm:
    if: github.event_name != 'pull_request_target' || (github.event_name == 'pull_request_target' && github.event.pull_request.merged == true)
    uses: ./.github/workflows/npm_update.yml
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_SUDO: ${{ secrets.SSH_SUDO }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_PORT: ${{ secrets.SSH_PORT }}