name: Server Initialization
on:
  workflow_dispatch: # 允许手动触发此工作流

jobs:
  init-server:
    name: Initialize Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify files exist
        run: |
          echo "Checking if required files exist..."
          ls -la script/ || echo "script/ directory not found"
          ls -la script/webserver.service || echo "webserver.service not found"
          ls -la script/cdmga_nginx.conf || echo "cdmga_nginx.conf not found"

      - name: Install dependencies on remote server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_SUDO }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            # 更新包管理器
            apt-get update -y
            
            # 安装 Java 17
            apt-get install -y openjdk-17-jdk
            java -version
            
            # 安装 Nginx
            apt-get install -y nginx
            nginx -v
            
            # 创建应用目录和日志目录
            mkdir -p /var/www/app-jars/
            mkdir -p /var/www/app-jars-backup/
            mkdir -p /var/www/CDMGA-ui/
            mkdir -p /var/www/CDMGA-backup/
            mkdir -p /var/www/logs/
            mkdir -p /var/www/config/
            
            
            echo "All dependencies installed successfully!"

      - name: Transfer script files to server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_SUDO }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          source: "script/*"
          target: "/var/www/"

      - name: Deploy and enable Systemd service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_SUDO }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            # 复制 Systemd 服务文件到正确位置
            cp /var/www/script/webserver.service /etc/systemd/system/
            
            # 重新加载 Systemd 配置
            systemctl daemon-reload
            
            # 启用服务（开机自启）
            systemctl enable webserver.service
            
            echo "Systemd service deployed and enabled successfully!"

      - name: Copy and enable Nginx configuration
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_SUDO }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            # 添加执行权限
            # chmod +x /var/www/script/restart_vue_cdmga.sh
            # chmod +x /var/www/script/restart_mvn_cdmga.sh

            # 复制 Nginx 配置文件
            cp /var/www/script/cdmga_nginx.conf /etc/nginx/sites-available/
            
            # 创建符号链接以启用站点（如果尚未存在）
            if [ ! -f /etc/nginx/sites-enabled/cdmga_nginx.conf ]; then
              ln -s /etc/nginx/sites-available/cdmga_nginx.conf /etc/nginx/sites-enabled/
            fi
            
            # 测试 Nginx 配置
            nginx -t
            
            # 重启 Nginx 服务
            systemctl restart nginx
            
            echo "Nginx configuration applied successfully!"

      - name: Verify installation
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_SUDO }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            echo "=== Verification ==="
            echo "Java version:"
            java -version
            echo ""
            echo "Nginx status:"
            systemctl status nginx --no-pager
            echo ""
            echo "Webserver service status:"
            systemctl status webserver.service --no-pager
            echo ""
            echo "Directory permissions:"
            ls -la /var/www/
            echo ""
            echo "Systemd service file:"
            ls -la /etc/systemd/system/webserver.service