name: mvn-update 
on: push
  # push:
  #   paths:
  #     - 'webpage/**'

jobs:
  mvn-build:
    name: mvn build
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: webpage
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17' # 根据您的项目需求调整Java版本
        distribution: 'temurin'
        cache: 'maven'
    
    - name: Build with Maven
      run: mvn clean package -P prod
      
    - name: List JAR file  # 帮助确认JAR包的位置和名称
      run: ls -la target/*.jar

    - name: Deploy JAR to Aliyun ECS via SCP
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_SUDO }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT || 22 }}  
        source: "webpage/target/*.jar"  # 上传打包好的JAR文件
        target: /var/www/app-jars/  # 服务器上存放JAR包的目录
        debug: true

    - name: Run deployment script via SSH
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_SUDO }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT || 22 }}  
        script: /var/www/script/restart_mvn_cdmga.sh